baseURL = "https://rehanvipin.github.io/"
languageCode = "en"
title = "Black and White"
theme = "anatole"
enableEmoji = "true"
summarylength = 10

[params]
title = "I'm Rehan Vipin 🌌"
author = "Rehan Vipin"
description = "These are my deeds, ambitions and perspectives"
profilePicture = "images/firstMask.jpg"
favicon = "favicon/"
displayMode = "dark"
mainSections = ["post"]

[menu]
    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

    [[menu.main]]
    name = "Posts"
    identifier = "Posts"
    weight = 200
    url = "/post/"

[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/rehan-vipin/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/rehanvipin"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:rehanvipin@outlook.com"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/rehan_vipin"